[sources.docker]
type = "docker_logs"

[transforms.parse_logs]
type = "remap"
inputs = ["docker"]
source = '''
  parsed, err = parse_json(.message)
  if err == null {
    . = merge(., parsed)
  }
'''

[sinks.victorialogs]
type = "http"
inputs = ["parse_logs"]
uri = "http://victoria-logs:9428/insert/jsonline?_stream_fields=container_name,stream"
encoding.codec = "json"
